# Generated by Django 4.1.5 on 2023-01-14 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_item_date_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideosDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/')),
                ('titleImage', models.ImageField(upload_to='titleImage/')),
                ('thumbnailImage', models.ImageField(upload_to='thumbnailImage/')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=2000)),
                ('year', models.IntegerField(null=True)),
                ('genre', models.CharField(max_length=100, null=True)),
                ('type', models.CharField(choices=[('Music Videos', 'Musicvideos'), ('Web Series', 'Webseries'), ('Movies', 'Movies'), ('Trailers', 'Trailers'), ('Kids', 'Kids'), ('Devotional', 'Devotional')], default='Music Videos', max_length=12)),
                ('trailer', models.FileField(null=True, upload_to='tailers/', verbose_name='Trailer')),
                ('video', models.FileField(null=True, upload_to='videos/%y', verbose_name='Video')),
            ],
        ),
    ]
